# Generated by Django 4.2.14 on 2024-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xds_api', models.CharField(default='http://localhost:8080/', help_text='Enter the XDS api endpoint to query', max_length=200)),
                ('target_elrr_api', models.CharField(default='http://localhost:9200/', help_text='Enter the ELRR api endpoint to query', max_length=200)),
                ('target_eccr_api', models.CharField(default='http://localhost:9200/', help_text='Enter the ECCR api endpoint to query', max_length=200)),
            ],
        ),
    ]
