# Generated by Django 4.2.15 on 2024-08-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('configuration', '0001_initial'), ('configuration', '0002_configuration_manager_group_and_more')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xds_api', models.CharField(default='http://localhost:8100/', help_text='Enter the XDS api endpoint to query', max_length=200)),
                ('target_elrr_api', models.CharField(default='http://localhost:9200/', help_text='Enter the ELRR api endpoint to query', max_length=200)),
                ('target_eccr_api', models.CharField(default='http://localhost:9200/', help_text='Enter the ECCR api endpoint to query', max_length=200)),
                ('manager_group', models.ManyToManyField(help_text='Groups that should have Talent Manger permissions', related_name='manager_config', to='auth.group')),
                ('org_admin_group', models.ManyToManyField(help_text='Groups that should have Org Admin permissions', related_name='org_admin_config', to='auth.group')),
                ('target_ldss_api', models.CharField(default='http://localhost:8010/', help_text='Enter the LDSS admin endpoint', max_length=200)),
                ('target_xms_api', models.CharField(default='http://localhost:8000/', help_text='Enter the XMS api endpoint to query', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='XIS Admin', help_text='Enter a human readable name for this Admin', max_length=200, unique=True)),
                ('target', models.CharField(default='http://localhost:8000/admin/', help_text='Enter the Admin endpoint', max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='configuration.configuration')),
            ],
        ),
    ]
