# Generated by Django 4.2.14 on 2024-07-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='manager_group',
            field=models.ManyToManyField(help_text='Groups that should have Talent Manger permissions', related_name='manager_config', to='auth.group'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='org_admin_group',
            field=models.ManyToManyField(help_text='Groups that should have Org Admin permissions', related_name='org_admin_config', to='auth.group'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='target_ldss_api',
            field=models.CharField(default='http://localhost:8010/', help_text='Enter the LDSS admin endpoint', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='target_xms_api',
            field=models.CharField(default='http://localhost:8000/', help_text='Enter the XMS api endpoint to query', max_length=200),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='target_xds_api',
            field=models.CharField(default='http://localhost:8100/', help_text='Enter the XDS api endpoint to query', max_length=200),
        ),
        migrations.CreateModel(
            name='AdminConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='XIS Admin', help_text='Enter a human readable name for this Admin', max_length=200, unique=True)),
                ('target', models.CharField(default='http://localhost:8000/admin/', help_text='Enter the Admin endpoint', max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='configuration.configuration')),
            ],
        ),
    ]
