# Generated by Django 4.2.23 on 2025-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_adminconfiguration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lrs_endpoint',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS Endpoint to send data to', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='lrs_password',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS HTTP Basic Auth password', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='lrs_platform',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS Platform, leave blank for All', max_length=200),
        ),
        migrations.AddField(
            model_name='configuration',
            name='lrs_username',
            field=models.CharField(blank=True, help_text='Enter the xAPI LRS HTTP Basic Auth username', max_length=200),
        ),
    ]
