# Generated by Django 4.2.26 on 2025-11-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_configuration_lrs_endpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Upload the logo image', upload_to='logos/')),
                ('welcome_message', models.CharField(default='Welcome to the EDLM Portal', help_text='Enter the welcome message for the portal', max_length=1000)),
            ],
        ),
    ]
