# Generated by Django 4.2.24 on 2025-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_configuration_lrs_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='target_elrr_api_key',
            field=models.TextField(blank=True, help_text='Enter the API Key to use for communicating with ELRR Services.'),
        ),
    ]
