# Generated by Django 4.2.26 on 2025-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_uiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiconfiguration',
            name='portal_name',
            field=models.CharField(default='EDLM Portal', help_text='Enter the name of the portal', max_length=200),
        ),
    ]
