# Generated by Django 4.2.27 on 2025-12-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_configuration_target_elrr_api_key'),
        ('configuration', '0006_uiconfiguration_portal_name'),
    ]

    operations = [
    ]
