# Generated by Django 4.2.15 on 2024-08-14 22:25

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vacancy_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('vacancy_key_hash', models.CharField(max_length=255)),
                ('JobTitle', models.CharField(max_length=255)),
                ('JobGrade', models.CharField(blank=True, max_length=255, null=True)),
                ('AgencyContactEmail', models.EmailField(blank=True, max_length=255, null=True)),
                ('AgencyContactPhone', models.CharField(blank=True, max_length=255, null=True)),
                ('ApplicationCloseDate', models.DateTimeField(blank=True, null=True)),
                ('DepartmentName', models.CharField(blank=True, max_length=255, null=True)),
                ('AppointmentType', models.CharField(blank=True, max_length=255, null=True)),
                ('JobCategory', models.TextField(blank=True, null=True)),
                ('JobCompetencies', models.TextField(blank=True, null=True)),
                ('JobCredentials', models.TextField(blank=True, null=True)),
                ('JobLocation', models.TextField(blank=True, null=True)),
                ('JobPostingID', models.CharField(max_length=255)),
                ('JobPostingSite', models.URLField(max_length=255)),
                ('OrganizationName', models.CharField(max_length=255)),
                ('PositionEndDate', models.DateTimeField(blank=True, null=True)),
                ('PositionStartDate', models.DateTimeField(blank=True, null=True)),
                ('PublicationStartDate', models.DateTimeField(blank=True, null=True)),
                ('PromotionPotential', models.CharField(blank=True, max_length=255, null=True)),
                ('ProviderName', models.CharField(max_length=255)),
                ('Qualifications', models.TextField(blank=True, null=True)),
                ('Relocation', models.CharField(blank=True, max_length=255, null=True)),
                ('TravelRequired', models.CharField(blank=True, max_length=255, null=True)),
                ('UIDUnitIdentifiers', models.CharField(max_length=255)),
                ('WorkSchedule', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='external.job')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
            },
        ),
    ]
