# Generated by Django 4.2.16 on 2025-06-12 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='AgencyContactEmail',
            field=models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='AgencyContactPhone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='AppointmentType',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='DepartmentName',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobCategory',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobCompetencies',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobCredentials',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobGrade',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobLocation',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobPostingID',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobPostingSite',
            field=models.URLField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='JobTitle',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='OrganizationName',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='PromotionPotential',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='ProviderName',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Qualifications',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='Relocation',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='TravelRequired',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='UIDUnitIdentifiers',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='WorkSchedule',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_key',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_key_hash',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
    ]
