# Generated by Django 4.2.15 on 2024-08-23 19:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_initial'), ('api', '0003_remove_profileanswer_fully_unique_answer_and_more'), ('api', '0004_candidatelist_alter_profileanswer_options_and_more'), ('api', '0005_candidatelist_role_and_more'), ('api', '0006_trainingplan_candidatelist_competency_and_more')]

    initial = True

    dependencies = [
        ('external', '0002_remove_course_id_remove_job_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.profilequestion')),
                ('selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.profileanswer')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilequestion',
            constraint=models.UniqueConstraint(fields=('active', 'order'), name='unique_active_question_order'),
        ),
        migrations.AddConstraint(
            model_name='profilequestion',
            constraint=models.UniqueConstraint(fields=('active', 'order', 'question'), name='fully_unique_question'),
        ),
        migrations.AddField(
            model_name='profileanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.profilequestion'),
        ),
        migrations.AddConstraint(
            model_name='profileresponse',
            constraint=models.UniqueConstraint(fields=('question', 'submitted_by'), name='unique_question_response'),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_answer_order'),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'order', 'answer'), name='fully_unique_answer'),
        ),
        migrations.RemoveConstraint(
            model_name='profileanswer',
            name='fully_unique_answer',
        ),
        migrations.RemoveConstraint(
            model_name='profilequestion',
            name='unique_active_question_order',
        ),
        migrations.RemoveConstraint(
            model_name='profilequestion',
            name='fully_unique_question',
        ),
        migrations.AlterField(
            model_name='profilequestion',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profilequestion',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_question_answer'),
        ),
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('ranker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='vacancies.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profileanswer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='profilequestion',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='CandidateRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rank', models.PositiveSmallIntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
                ('candidate_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.candidatelist')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'rank'), name='unique_list_ranks'),
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'candidate'), name='unique_candidates_in_list'),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='external.job'),
        ),
        migrations.AlterField(
            model_name='candidatelist',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='vacancies.vacancy'),
        ),
        migrations.AddConstraint(
            model_name='candidatelist',
            constraint=models.CheckConstraint(check=models.Q(('role__isnull', True), ('competency__isnull', True), _connector='XOR'), name='role_or_competency'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='external.job'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_for_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
