# Generated by Django 4.2.14 on 2024-07-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileresponse',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='profilequestion',
            constraint=models.UniqueConstraint(fields=('active', 'order'), name='unique_active_question_order'),
        ),
        migrations.AddConstraint(
            model_name='profilequestion',
            constraint=models.UniqueConstraint(fields=('active', 'order', 'question'), name='fully_unique_question'),
        ),
        migrations.AddField(
            model_name='profileanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.profilequestion'),
        ),
        migrations.AddConstraint(
            model_name='profileresponse',
            constraint=models.UniqueConstraint(fields=('question', 'submitted_by'), name='unique_question_response'),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_answer_order'),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'order', 'answer'), name='fully_unique_answer'),
        ),
    ]
