# Generated by Django 4.2.14 on 2024-07-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profileanswer',
            name='fully_unique_answer',
        ),
        migrations.RemoveConstraint(
            model_name='profilequestion',
            name='unique_active_question_order',
        ),
        migrations.RemoveConstraint(
            model_name='profilequestion',
            name='fully_unique_question',
        ),
        migrations.AlterField(
            model_name='profilequestion',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='profilequestion',
            name='question',
            field=models.TextField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='profileanswer',
            constraint=models.UniqueConstraint(fields=('question', 'answer'), name='unique_question_answer'),
        ),
    ]
