# Generated by Django 4.2.14 on 2024-08-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_profileanswer_fully_unique_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.TextField()),
                ('ranker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='vacancies.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='profileanswer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='profilequestion',
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='CandidateRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('rank', models.PositiveSmallIntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
                ('candidate_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='api.candidatelist')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'rank'), name='unique_list_ranks'),
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'candidate'), name='unique_candidates_in_list'),
        ),
    ]
