# Generated by Django 4.2.15 on 2024-08-14 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidatelist_alter_profileanswer_options_and_more'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelist',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='vacancies.vacancy'),
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'rank'), name='unique_list_ranks'),
        ),
        migrations.AddConstraint(
            model_name='candidateranking',
            constraint=models.UniqueConstraint(fields=('candidate_list', 'candidate'), name='unique_candidates_in_list'),
        ),
    ]
