# Generated by Django 4.2.15 on 2024-08-23 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        ('external', '0002_remove_course_id_remove_job_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_candidatelist_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='candidatelist',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='external.job'),
        ),
        migrations.AlterField(
            model_name='candidatelist',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='vacancies.vacancy'),
        ),
        migrations.AddConstraint(
            model_name='candidatelist',
            constraint=models.CheckConstraint(check=models.Q(('role__isnull', True), ('competency__isnull', True), _connector='XOR'), name='role_or_competency'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to='external.job'),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans_for_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
