# Generated by Django 4.2.24 on 2025-10-23 20:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('external', '0006_competency_ksa'),
        ('api', '0008_learningplan_learningplancompetency_learningplangoal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlanGoalCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plan_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.learningplangoal')),
                ('xds_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xds_courses', to='external.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
