# Generated by Django 4.2.24 on 2025-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_learningplangoalcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplangoal',
            name='elrr_goal_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningplangoalcourse',
            name='elrr_course_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningplangoalksa',
            name='elrr_ksa_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
