# Generated by Django 4.2.24 on 2025-12-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_learningplangoal_elrr_goal_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplangoal',
            name='timeline',
            field=models.CharField(choices=[('1-3 months', '1-3 months'), ('3-6 months', '3-6 months'), ('6-9 months', '6-9 months'), ('9-12 months', '9-12 months'), ('12-18 months', '12-18 months'), ('18-24 months', '18-24 months'), ('2-2.5 years', '2-2.5 years'), ('2.5-3 years', '2.5-3 years'), ('3-3.5 years', '3-3.5 years'), ('3.5-4 years', '3.5-4 years'), ('4-4.5 years', '4-4.5 years'), ('4.5-5 years', '4.5-5 years')], max_length=20),
        ),
    ]
