# Generated by Django 4.2.24 on 2025-12-02 19:13

from django.db import migrations

def forwards_func(apps, schema_editor):
    LearningPlanGoal = apps.get_model('api', 'LearningPlanGoal')
    LearningPlanGoal.objects.filter(timeline='1-3 months').update(timeline='3')
    LearningPlanGoal.objects.filter(timeline='3-6 months').update(timeline='6')
    LearningPlanGoal.objects.filter(timeline='6-9 months').update(timeline='9')
    LearningPlanGoal.objects.filter(timeline='9-12 months').update(timeline='12')
    LearningPlanGoal.objects.filter(timeline='12-18 months').update(timeline='18')
    LearningPlanGoal.objects.filter(timeline='18-24 months').update(timeline='24')
    LearningPlanGoal.objects.filter(timeline='2-2.5 years').update(timeline='30')
    LearningPlanGoal.objects.filter(timeline='2.5-3 years').update(timeline='36')
    LearningPlanGoal.objects.filter(timeline='3-3.5 years').update(timeline='42')
    LearningPlanGoal.objects.filter(timeline='3.5-4 years').update(timeline='48')
    LearningPlanGoal.objects.filter(timeline='4-4.5 years').update(timeline='54')
    LearningPlanGoal.objects.filter(timeline='4.5-5 years').update(timeline='60')
    
def reverse_func(apps, schema_editor):
    LearningPlanGoal = apps.get_model('api', 'LearningPlanGoal')
    LearningPlanGoal.objects.filter(timeline='3').update(timeline='1-3 months')
    LearningPlanGoal.objects.filter(timeline='6').update(timeline='3-6 months')
    LearningPlanGoal.objects.filter(timeline='9').update(timeline='6-9 months')
    LearningPlanGoal.objects.filter(timeline='12').update(timeline='9-12 months')
    LearningPlanGoal.objects.filter(timeline='18').update(timeline='12-18 months')
    LearningPlanGoal.objects.filter(timeline='24').update(timeline='18-24 months')
    LearningPlanGoal.objects.filter(timeline='30').update(timeline='2-2.5 years')
    LearningPlanGoal.objects.filter(timeline='36').update(timeline='2.5-3 years')
    LearningPlanGoal.objects.filter(timeline='42').update(timeline='3-3.5 years')
    LearningPlanGoal.objects.filter(timeline='48').update(timeline='3.5-4 years')
    LearningPlanGoal.objects.filter(timeline='54').update(timeline='4-4.5 years')
    LearningPlanGoal.objects.filter(timeline='60').update(timeline='4.5-5 years')

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_learningplangoal_timeline'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
