# Generated by Django 4.2.24 on 2025-12-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_convert_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningplangoal',
            name='timeline',
            field=models.IntegerField(choices=[(3, '1-3 months'), (6, '3-6 months'), (9, '6-9 months'), (12, '9-12 months'), (18, '12-18 months'), (24, '18-24 months'), (30, '2-2.5 years'), (36, '2.5-3 years'), (42, '3-3.5 years'), (48, '3.5-4 years'), (54, '4-4.5 years'), (60, '4.5-5 years')]),
        ),
    ]
