# Generated by Django 4.2.27 on 2025-12-11 19:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_learningplangoal_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('NEW', 'New Application'), ('RENEWAL', 'Renewal Application')], help_text='Type of application: New or Renewal', max_length=20)),
                ('position', models.CharField(choices=[('SAPR_VA', 'SAPR VA (Victim Advocate)'), ('SARC/SAPR_PM', 'SARC / SAPR PM')], help_text='Position being applied for: SAPR VA or SARC / SAPR PM', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the application', max_length=50)),
                ('policy', models.CharField(default='dod-xxxx', help_text='Policy reference number', max_length=100)),
                ('application_version', models.IntegerField(default=1, help_text='Version number of the application')),
                ('first_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('last_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('middle_initial', models.CharField(blank=True, max_length=1, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('affiliation', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('mili_status', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='Military Status')),
                ('rank', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('grade', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('command_unit', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('installation', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('has_mil_gov_work_email', models.BooleanField(default=False, help_text='Indicates if user has military/government work email')),
                ('other_sarc_email', models.EmailField(blank=True, max_length=254, verbose_name='Other Email')),
                ('dsn_code', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='DSN Code')),
                ('work_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('work_phone_ext', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='Work Phone Extension')),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certification file', null=True, upload_to='applications/certificates/')),
                ('certification_awarded_date', models.DateField(blank=True, help_text='Date when certification was awarded', null=True)),
                ('certification_expiration_date', models.DateField(blank=True, help_text='Date when certification expires', null=True)),
                ('no_experience_needed', models.BooleanField(default=False, help_text='Check if no experience is needed for this application')),
                ('supervisor_last_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('supervisor_first_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('sarc_last_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='SARC Last Name')),
                ('sarc_first_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='SARC First Name')),
                ('sarc_email', models.EmailField(blank=True, max_length=254, verbose_name='SARC Email')),
                ('commanding_officer_last_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='CO Last Name')),
                ('commanding_officer_first_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='CO First Name')),
                ('commanding_officer_email', models.EmailField(blank=True, max_length=254, verbose_name='CO Email')),
                ('co_same_as_supervisor', models.BooleanField(default=False, help_text='Check if commanding officer is the same as supervisor', verbose_name='CO same as Supervisor')),
                ('code_of_ethics_acknowledgement', models.BooleanField(default=False, help_text='Applicant acknowledges code of ethics', verbose_name='Code of Ethics Acknowledgement')),
                ('final_submission', models.BooleanField(default=False, help_text='Indicates the application has been submitted')),
                ('final_submission_stamp', models.DateTimeField(blank=True, help_text='Timestamp of final submission', null=True)),
                ('applicant', models.ForeignKey(help_text='The user whom this application is for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this experience')),
                ('position_name', models.CharField(help_text='Title/name of the position', max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('start_date', models.DateField(help_text='Start date of experience')),
                ('end_date', models.DateField(blank=True, help_text='End date of experience (blank if ongoing)', null=True)),
                ('advocacy_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Number of advocacy hours accumulated', max_digits=10)),
                ('marked_for_evaluation', models.BooleanField(default=False, help_text='Flag indicating if this experience should be evaluated')),
                ('supervisor_last_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('supervisor_first_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('supervisor_not_available', models.BooleanField(default=False, help_text='Check if supervisor is not available for verification', verbose_name='Supervisor Not Available')),
                ('proof_file', models.FileField(blank=True, help_text='Upload proof of experience document', null=True, upload_to='applications/experience_proofs/')),
                ('application', models.ForeignKey(help_text='The application this experience belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='api.application')),
            ],
            options={
                'verbose_name': 'Application Experience',
                'verbose_name_plural': 'Application Experiences',
                'ordering': ['display_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display this course')),
                ('category', models.CharField(blank=True, help_text='Category or competency area (e.g., competency)', max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('xds_course_id', models.CharField(blank=True, help_text='Reference ID to external course table (XDS system)', max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')], verbose_name='XDS Course ID')),
                ('completion_date', models.DateField(help_text='Date when the course was completed')),
                ('clocked_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Number of hours for this course', max_digits=6)),
                ('application', models.ForeignKey(help_text='The application this course belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.application')),
            ],
            options={
                'verbose_name': 'Application Course',
                'verbose_name_plural': 'Application Courses',
                'ordering': ['display_order', '-completion_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='Comment text', validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='The application this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.application')),
                ('reviewer', models.ForeignKey(help_text='The user who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='application_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Comment',
                'verbose_name_plural': 'Application Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
