# Generated by Django 4.2.27 on 2025-12-16 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_application_applicationexperience_applicationcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('additional_info_needed', 'Additional Information Needed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the application', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationcourse',
            name='clocked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Number of hours for this course', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0, message='Hours cannot be negative')]),
        ),
        migrations.AlterField(
            model_name='applicationexperience',
            name='advocacy_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Number of advocacy hours accumulated', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0, message='Hours cannot be negative')]),
        ),
    ]
