# Generated by Django 4.2.27 on 2025-12-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_application_applicationexperience_applicationcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, choices=[('SAPR_Program_Administrator', 'SAPR Program Administrator'), ('SAPR_VA', 'SAPR VA'), ('Principal_SARC', 'Principal SARC'), ('Supervisory_SARC', 'Supervisory SARC'), ('Collateral_Duty_SARC', 'Collateral Duty SARC'), ('Special_Assignment_SARC', 'Special Assignment SARC'), ('Collateral_Duty_SAPR_VA', 'Collateral Duty SAPR VA'), ('Special_Assignment_SAPR_VA', 'Special Assignment SAPR VA')], help_text='Position being applied for: SAPR VA or SARC / SAPR PM', max_length=40),
        ),
    ]
