# Generated by Django 4.2.27 on 2025-12-11 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_application_applicationexperience_applicationcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_type',
            field=models.CharField(blank=True, choices=[('NEW', 'New Application'), ('RENEWAL', 'Renewal Application')], help_text='Type of application: New or Renewal', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_version',
            field=models.IntegerField(blank=True, default=1, help_text='Version number of the application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certificate_file',
            field=models.FileField(help_text='Upload certification file', null=True, upload_to='applications/certificates/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='certification_awarded_date',
            field=models.DateField(help_text='Date when certification was awarded', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='certification_expiration_date',
            field=models.DateField(help_text='Date when certification expires', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='final_submission',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates the application has been submitted'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='policy',
            field=models.CharField(blank=True, default='dod-xxxx', help_text='Policy reference number', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, choices=[('SAPR_VA', 'SAPR VA (Victim Advocate)'), ('SARC/SAPR_PM', 'SARC / SAPR PM')], help_text='Position being applied for: SAPR VA or SARC / SAPR PM', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current status of the application', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationcomment',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment text', validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='applicationcourse',
            name='clocked_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Number of hours for this course', max_digits=6),
        ),
        migrations.AlterField(
            model_name='applicationcourse',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date when the course was completed'),
        ),
    ]
