# Generated by Django 4.2.27 on 2025-12-11 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_application_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certification_awarded_date',
            field=models.DateField(blank=True, help_text='Date when certification was awarded', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='certification_expiration_date',
            field=models.DateField(blank=True, help_text='Date when certification expires', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='code_of_ethics_acknowledgement',
            field=models.BooleanField(help_text='Applicant acknowledges code of ethics', verbose_name='Code of Ethics Acknowledgement'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid character used', regex='^([\\x09\\x0A\\x0D\\x20-\\x7E]|[\\xC2-\\xDF]|[\\xE0\\xA0-\\xBF]|[\\xE1-\\xEC\\xEE\\xEF]{2}|[\\xED\\x80-\\x9F]|[\\xF0\\x90-\\xBF]{2}|[\\xF1-\\xF3]{3}|[\\xF4\\x80-\\x8F]{2})*$')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='no_experience_needed',
            field=models.BooleanField(blank=True, default=False, help_text='Check if no experience is needed for this application'),
        ),
    ]
