# Generated by Django 4.2.27 on 2026-01-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_application_position'),
        ('api', '0015_alter_application_status_and_more'),
    ]

    operations = [
    ]
