# Generated by Django 4.2.27 on 2026-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='code_of_ethics_acknowledged_stamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when code of ethics acknowledged', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='code_of_ethics_acknowledgement',
            field=models.BooleanField(default=False, help_text='Applicant acknowledges code of ethics', verbose_name='Code of Ethics Acknowledgement'),
        ),
    ]
