# Generated by Django 4.2.27 on 2025-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_application_certification_awarded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload certification file', null=True, upload_to='applications/certificates/'),
        ),
    ]
