# Generated by Django 4.2.27 on 2025-12-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_application_certificate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='code_of_ethics_acknowledgement',
            field=models.BooleanField(help_text='Applicant acknowledges code of ethics', null=True, verbose_name='Code of Ethics Acknowledgement'),
        ),
    ]
