# Generated by Django 4.2.27 on 2025-12-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_application_code_of_ethics_acknowledgement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='code_of_ethics_acknowledgement',
            field=models.BooleanField(default=False, help_text='Applicant acknowledges code of ethics', verbose_name='Code of Ethics Acknowledgement'),
            preserve_default=False,
        ),
    ]
